#!/bin/bash
# patch-clean by @nieltg

. $(dirname "${BASH_SOURCE[0]}")/common.sh

pa_app_init "" "$@"

_clean_loop ()
{
	# ( base_repo ) => nul; clean repos to its original state
	
	# [ -d "${1}" ] || pa_app_assert
	
	pa_log_progress_start "Cleaning ${1}... "
	( cd "${ANDROID_BUILD_TOP}/${1}" ; git checkout . ; git clean -f )
	pa_log_progress_fini "$?" "${1}"
}

pa_eng_repo_loop "_clean_loop"

