#!/bin/bash
# patch-clean by @nieltg

. $(dirname "${BASH_SOURCE[0]}")/common.sh

pa_app_init "" "$@"

_patch_loop ()
{
	# ( base_repo ) => nul; apply patch to specified repo
	
	# [ -d "${1}" ] || pa_app_assert
	
	# TODO: PA_ENG_PATCH_DIR in common.sh should be abspath
	local n_absp="$(realpath "${1}")"
	
	local n_repo="$(pa_eng_parse_repo "${1}")"
	local n_titl="$(pa_eng_parse_title "${1}")"
	
	pa_log_progress_start "Applying ${n_titl}... "
	( cd "${ANDROID_BUILD_TOP}/${n_repo}" ; patch -p1 < "${n_absp}" )
	pa_log_progress_fini "$?" "${n_titl}"
}

pa_eng_patch_loop "_patch_loop"

